name: Deploy Quasar SPA to GitHub Pages

on:
  push:
    branches: [ "cicd" ] # 👈 เปลี่ยนเป็น branch ที่คุณต้องการ เช่น "cicd"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ให้สิทธิ์ push ไปที่ branch gh-pages ได้

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ใช้ Node.js เวอร์ชันใหม่ที่ Quasar รองรับ

      - name: Install dependencies
        run: npm install

      - name: Build Quasar SPA
        run: npx quasar build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}  # ใช้ token อัตโนมัติของ GitHub
          publish_dir: dist/spa  # ที่อยู่ของไฟล์ build ที่จะ deploy